env:
    global:
        - REPO_DIR=cffi
        - PLAT=x86_64
        - MANYLINUX_URL="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
        - WHEELHOUSE_UPLOADER_USERNAME=travis-worker

language: python
services: docker
os: linux

jobs:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
      - stage: build wheel
        env:
          - MB_PYTHON_VERSION=3.7
          - PLAT=x86_64

      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.7
          - PLAT=aarch64
          - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
          - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}

before_install:
    - sudo apt-get install mercurial
    - hg clone https://foss.heptapod.net/pypy/cffi
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
          CONTAINER="pre-release";
          BUILD_COMMIT=${DAILY_COMMIT:-$BUILD_COMMIT};
      else
          CONTAINER=wheels;
          UPLOAD_ARGS="--no-update-index";
      fi
    #- BUILD_DEPENDS="$NP_BUILD_DEP $CYTHON_BUILD_DEP $PYBIND11_BUILD_DEP"
    - TEST_DEPENDS="pytest pycparser"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - build_wheel $REPO_DIR $PLAT
    - ls ${TRAVIS_BUILD_DIR}/wheelhouse || true
    - ls wheelhouse || true

script:
    - install_run $PLAT
after_success:
    - pip install twine
    - twine upload ${TRAVIS_BUILD_DIR}/wheelhouse/*
